### PR TITLE
Use keycode to provide better cross browser support

### PR DESCRIPTION
**Pull request by pythonandchips**
As some browsers send the keycode in different event properties this
add keycode to figure our what key was pressed by the user and give a
constant value.

### CODE REVIEW

**Comment by afcapel** [comment]
@pythonandchips thanks for the pull request!

Did you find any specific issue that required this library? 

We use the [event.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) property instead of the [event.keycode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode), which should be more reliable across browsers. 

Also we are only interested in 5 keys, so if there's a small discrepancy between browsers it might be simpler modifying the `switch/case` clause than introducing a dependency.

Still happy to merge this if `event.key` doesn't fit the bill, just trying to understand the problem better.

**Comment by pythonandchips** [comment]
If I remember correctly it was an issue with IE11 that was causing the issue, although I honestly can't completely remember. Adding the keys for IE11 would work as well and reduce the need for the library.

**Comment by miketheman** [comment]
I'd add it appears that MDN has deprecated `keyCode` - https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode - rather suggests using `https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code` - so it's possible the action here is to convert `switch (event.key)` to `switch (event.code)` and no other changes should be necessary.

**Comment by drnic** [comment]
I'll close this PR for now. If we want to revisit this topic, please do so.

**Pull request closed without merging**
