### PR TITLE
Eval script tags returned from server

### PR DESCRIPTION
**Pull request by cmer**
This can be extremely useful to position the dropdown when just CSS won't do, for example.

I ran into such an issue, and returning a small bit of Javascript from the server saved me.

### CODE REVIEW

**Comment by glaszig** [comment]
this will require a csp with `unsafe-eval` afaik.

how [rails-ujs](https://github.com/rails/rails/blob/4505c2f508418e40c2cf82701cc9144cb7e4e83d/actionview/app/assets/javascripts/rails-ujs/utils/ajax.coffee#L69-L72) does it:

```js
script = document.createElement('script')
script.setAttribute('nonce', cspNonce())
script.text = response
document.head.appendChild(script).parentNode.removeChild(script)
```

**Comment by cmer** [comment]
Makes sense. I updated the code. Let me know what you think!

**Comment by cmer** [comment]
I messed something up, still working on this...

**Comment by cmer** [comment]
I ended up solving my problem in a much better way. I just created a Stimulus controller instead. In case it's useful to anyone, I just added the controller on the element being returned. Here's my controller:

```javascript
import { Controller } from "@hotwired/stimulus"

// Hack to position the dropdown outside of the parent div to allow it to overflow beyond the y axis
// See: https://stackoverflow.com/a/74749062
// and: https://codepen.io/tammibriggs/pen/gOKyWgG

export default class extends Controller {
  connect() {
    let dropdown = this.element;
    let parent = dropdown.parentElement;
    dropdown.style.left = parent.left + 'px';
    dropdown.style.position = 'fixed';
  }
}
```

**Pull request closed without merging**
