### PR TITLE
Big merge of latest PR's, update of README.md

### PR DESCRIPTION
**Pull request by pruzicka**
This PR is a merge of
- last few Dependabot's PRs
- support for Stimulus 2.0, via #26
- update of README.md usage of CSS classes in example via   #18 
- update of README.md, new Stimulus 2.0 syntax for targets in example

### CODE REVIEW

**Comment by drnic** [comment]
@pruzicka I have some PRs I can submit too, and would prefer to build off your stimulus2 work. I've been using a hard fork of this repo for a while and would like to share some improvements back.

@afcapel do you have a preference for maintainership of this repo going forward? Want to grant git commit rights/npm rights to @pruzicka and/or myself?

**Comment by afcapel** [comment]
@pruzicka Thanks for this.

@drnic thanks for the offer, I've already given you acommit bit to the repository. @pruzicka do you want access yourself too?

I can also move the repository to an organization, so can also invite new maintainers yourself.

**Comment by drnic** [comment]
@afcapel thanks; re new org -- we can revisit that in future. You made a cool thing; you can have credit for awhile longer :)

**Comment by pruzicka** [comment]
> @pruzicka Thanks for this.
> 
> @drnic thanks for the offer, I've already given you acommit bit to the repository. @pruzicka do you want access yourself too?
> 
> I can also move the repository to an organization, so can also invite new maintainers yourself.

Hi, no I'm fine like this - happy user of this repo. Thank you

**Pull request merged**
